export const ADD_TO_FAV = 'ADD_TO_FAV'
export const DEL_FROM_FAV = 'DEL_FROM_FAV'
export const ADD_TO_HISTORY = 'ADD_TO_HISTORY'
export const DEL_FROM_HISTORY = 'DEL_FROM_HISTORY'
export const DEL_ALL_HISTORY = 'DEL_ALL_HISTORY'